# Testing putting all of the parameters in a file

seed = 42

render = true
animation_steps = 1000
video_path = "./animations/"

search_strategy = "random" # one of ["random","sweep"]

# Modelling Parameters
number_of_targets = 10
beamwidth_degrees = 10
radar_min_range_meters = 500
radar_max_range_meters = 500_000
xy_bins = 20
dwell_time_seconds = 200e-3
target_velocity_max_meters_per_second = 700
include_no_observations = true

# Filter Parameters
n_particles = 100
