# Testing putting all of the parameters in a file

seed = 42
write_model = true
model_path = "./models/figup13"

render = true
video_path = "./animations/test13"

search_strategy = "random" # one of ["random","sweep"]

train = true

# Solving Parameters
learning_rate = 1e-3
steps_per_sequence = 1000
train_sequences = 500
test_sequences = 20
epochs = 100
use_gpu = false
gpu_type = "Metal"        # one of ["CUDA","Metal"]


# Modelling Parameters
number_of_targets = 10
beamwidth_degrees = 10
radar_min_range_meters = 500
radar_max_range_meters = 500_000
xy_bins = 20
dwell_time_seconds = 200e-3
target_velocity_max_meters_per_second = 700
include_no_observations = true

# Filter Parameters
n_particles = 100
